# Header
menu:
  Home: /
  Tags: /tags
  Archives: /archives
  RSS: /atom.xml

# Content
excerpt_link: Leer más

# Sidebar
author:
  name: Jorge Zapata Guridi
  work: Software Engineer
  location: Seattle, USA
  avatar_url: /images/avatar.jpg

# Links:
links:
  - svg: ./source/svg/github.svg
    url: https://github.com/alimnios72
  - svg: ./source/svg/linkedin.svg
    url: https://www.linkedin.com/in/jorge-zapata-guridi-89b97523/
  - svg: ./source/svg/twitter.svg
    url: https://twitter.com/cacharro

# github comment 
git_commit:
  enable: false

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico
twitter: cacharro
google_analytics: UA-18116909-1
