# Header
menu:
  Home: /
  Front-End: /categories/front-end
  Back-End: /categories/back-end
  Tags: /tags
  Archives: /archives
  RSS: /atom.xml
  Acerca de: /about

# Content
excerpt_link: Leer más

# Sidebar
author:
  name: Jorge Zapata Guridi
  work: Software Engineer
  location: Seattle, USA
  avatar_url: /images/avatar.jpg

# Links:
links:
  - svg: ./source/svg/github.svg
    url: https://github.com/alimnios72
  - svg: ./source/svg/more.svg
    url: http://weibo.com/sanonz
  - svg: ./source/svg/twitter.svg
    url: https://twitter.com/cacharro

# github comment 
git_commit:
  enable: false


# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico
